-- Mini-SQL LL(1) Compiler Sample Queries
-- Designed for Demonstration, Academic Viva, and Automated Testing

-- 1. Simple Projection of all columns
SELECT * FROM employees;

-- 2. Single column selection
SELECT name FROM employees;

-- 3. Multiple column selection
SELECT name, salary FROM employees;

-- 4. Numeric filtering with greater than operator
SELECT name, salary FROM employees WHERE salary > 50000;

-- 5. Filtering and descending sort
SELECT name, salary FROM employees WHERE salary > 50000 ORDER BY salary DESC;

-- 6. String equality comparison
SELECT name, department FROM employees WHERE department = 'IT';

-- 7. Compound AND filtering with ascending sort
SELECT name, age, salary FROM employees WHERE age >= 25 AND salary <= 70000 ORDER BY age ASC;

-- 8. Duplicate projection (Demonstrates Projection Pruning in Optimizer)
SELECT name, salary, name FROM employees;

-- 9. Redundant predicate (Demonstrates Predicate Simplification in Optimizer)
SELECT name FROM employees WHERE salary > 50000 AND salary > 50000;

-- ====================================================================
-- SYNTAX ERROR EXAMPLES (Clean diagnostics generated by LL(1) Parser)
-- ====================================================================

-- Missing projection list:
-- SELECT FROM employees;

-- Missing FROM keyword:
-- SELECT name employees;

-- Missing table identifier:
-- SELECT name FROM;

-- Missing condition operand:
-- SELECT name FROM employees WHERE salary >;

-- ====================================================================
-- SEMANTIC ERROR EXAMPLES (Caught by Semantic Analyzer against SQLite)
-- ====================================================================

-- Unknown column in SELECT clause:
-- SELECT xyz FROM employees;

-- Unknown table in FROM clause:
-- SELECT name FROM students;

-- Unknown column in WHERE clause:
-- SELECT name FROM employees WHERE unknown_col > 100;

-- Type mismatch (comparing numeric column with string literal):
-- SELECT name FROM employees WHERE salary > 'high';
